// Mocks generated by Mockito 5.4.0 from annotations
// in app/test/infrastructure/repositories/authenticate_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/infrastructure/models/register/register.dart' as _i6;
import 'package:app/infrastructure/network/api/authenticate_api.dart' as _i3;
import 'package:app/infrastructure/network/dio/dio_client.dart' as _i2;
import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticateApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticateApi extends _i1.Mock implements _i3.AuthenticateApi {
  MockAuthenticateApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient => (super.noSuchMethod(
        Invocation.getter(#dioClient),
        returnValue: _FakeDioClient_0(
          this,
          Invocation.getter(#dioClient),
        ),
      ) as _i2.DioClient);
  @override
  _i4.Future<_i5.Response<dynamic>?>? authenticate(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #authenticate,
        [
          username,
          password,
        ],
      )) as _i4.Future<_i5.Response<dynamic>?>?);
  @override
  _i4.Future<_i5.Response<dynamic>?>? register(_i6.Register? request) =>
      (super.noSuchMethod(Invocation.method(
        #register,
        [request],
      )) as _i4.Future<_i5.Response<dynamic>?>?);
}
